const DELIVERY_PTR = {
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  PICKED_FROM_STORE: "PICKED_FROM_STORE",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
  ASSIGNED_TO_PARTNER: "ASSIGNED_TO_PARTNER",
  PENDING_REASSIGN: "PENDING_REASSIGN",
  PARTNER_ACCEPTED: "PARTNER_ACCEPTED",
};

module.exports = {
  DELIVERY_PTR,
};
