const ORDER_CONSTANTS = {
  PENDING: "PENDING",
  PROCESSING: "PROCESSING",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  SHIPPED: "SHIPPED",
  CREATED: "CREATED",
  DELIVERED: "DELIVERED",
  VENDOR_REJECTED: "VENDOR_REJECTED",
  VENDOR_ACCEPTED: "VENDOR_ACCEPTED",
};

const ORDER_HISTORY_CONSTANTS = {
  VENDOR: "VENDOR",
  CUSTOMER: "CUSTOMER",
  ADMIN: "ADMIN",
  SYSTEM: "SYSTEM",
};

module.exports = {
  ORDER_CONSTANTS,
  ORDER_HISTORY_CONSTANTS,
};
