const RESPONSE_CODE = {
  DEFAULT: "SUCCESS",
  LOGIN: "LOGIN",
  OTP: "OTP_VERIFIED",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  ERROR: "ERROR",
  ALERTS: "ALERTS",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  NOT_VERIFIED: "NOT_VERIFIED",
  DUPLICATE: "DUPLICATE",
  VENDOR_NOT_FOUND: "VENDOR_NOT_FOUND",
  CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
  DELIVERY_PARTNER_NOT_FOUND: "DELIVERY_PARTNER_NOT_FOUND",
  FAILURE: "FAILURE",
  REDIRECT: "REDIRECT",
};

module.exports = {
  RESPONSE_CODE,
};
